# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.5/containers/alpine/.devcontainer/base.Dockerfile


FROM python:3.9-alpine
RUN apk update
RUN apk add git
# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
